name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.16'
    - run: npm install # Instala todas las dependencias según package.json
    - run: npm install mysql2 formidable papaparse # Si necesitas instalar paquetes adicionales
